name: CI

on:
  push:
    branches:
      - main

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
          cache: 'pip'

      - name: Install dependencies
        run: |
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
          pip install -r requirements.txt
          pip install -e .

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Validate types with MyPy
        run: |
          mypy .
      - name: Test with pytest
        run: |
          pytest

#      - name: Build documentation
#        run: make html --directory docs/
